#
# Let's Chat Settings
#
# See defaults.yml for all available options
#

env: production

http:
  enable: true
  port: 8080

https:
  enable: false
  port: 5001
  key: key.pem
  cert: certificate.pem

xmpp:
  enable: false
  port: 5222
  host: localhost

database:
  uri: mongodb://localhost/letschat

secrets:
  cookie: secretsauce123

  local:
    dir: uploads

  s3:
    accessKeyId:
    secretAccessKey:
    bucket:
    region:

auth:
  providers: [local]

  local:
    enableRegistration: true
    salt: secretsauce123 # Required when upgrading from version < 0.3

  kerberos:
    realm: example.com
    use_ldap_authorization: false
    #ldap: # See defaults.yml for LDAP options

  ldap:
    # See defaults.yml for all LDAP options
